# GATE cylindrical PET system hierarchy
# World
#     |_ cylindricalPET
#                     |_RSector
#                             |_Module
#                                     |_Submodule
#                                               |_Crystal
#                                                       |_ LayerX

# Cylinder
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/geometry/setRmax 35 cm
/gate/cylindricalPET/geometry/setRmin 30 cm
/gate/cylindricalPET/geometry/setHeight 20 cm
/gate/cylindricalPET/vis/forceWireframe 1
/gate/cylindricalPET/vis/forceSolid 0
/gate/cylindricalPET/vis/setColor black
/gate/cylindricalPET/vis/setVisible 1

# Rsector
/gate/cylindricalPET/daughters/name PETrsector
/gate/cylindricalPET/daughters/insert box
/gate/PETrsector/setMaterial Air
/gate/PETrsector/geometry/setXLength 3 cm
/gate/PETrsector/geometry/setYLength 6 cm
/gate/PETrsector/geometry/setZLength 20 cm
/gate/PETrsector/vis/forceWireframe 1
/gate/PETrsector/vis/forceSolid 0
/gate/PETrsector/vis/setColor blue
/gate/PETrsector/vis/setVisible 1

/gate/PETrsector/placement/setTranslation 32.5 0 0 cm

# Module
/gate/PETrsector/daughters/name PETmodule
/gate/PETrsector/daughters/insert box
/gate/PETmodule/setMaterial Air
/gate/PETmodule/geometry/setXLength 3 cm
/gate/PETmodule/geometry/setYLength 6 cm
/gate/PETmodule/geometry/setZLength 20 cm
/gate/PETmodule/vis/forceWireframe 1
/gate/PETmodule/vis/forceSolid 0
/gate/PETmodule/vis/setColor blue
/gate/PETmodule/vis/setVisible 1


# Submodule
/gate/PETmodule/daughters/name PETsmod
/gate/PETmodule/daughters/insert box
/gate/PETsmod/setMaterial Air
/gate/PETsmod/geometry/setXLength 3 cm
/gate/PETsmod/geometry/setYLength 2 cm
/gate/PETsmod/geometry/setZLength 4 cm
/gate/PETsmod/vis/forceWireframe 1
/gate/PETsmod/vis/forceSolid 0
/gate/PETsmod/vis/setColor blue
/gate/PETsmod/vis/setVisible 1

# Crystal
/gate/PETsmod/daughters/name PETcrystal
/gate/PETsmod/daughters/insert box
/gate/PETcrystal/setMaterial Air
/gate/PETcrystal/geometry/setXLength 3 cm
/gate/PETcrystal/geometry/setYLength 1 cm
/gate/PETcrystal/geometry/setZLength 1 cm
/gate/PETcrystal/vis/forceWireframe 1
/gate/PETcrystal/vis/forceSolid 0
/gate/PETcrystal/vis/setColor yellow
/gate/PETcrystal/vis/setVisible 1

# Layer
/gate/PETcrystal/daughters/name PETlayer
/gate/PETcrystal/daughters/insert box
/gate/PETlayer/setMaterial LYSO
/gate/PETlayer/geometry/setXLength 3 cm
/gate/PETlayer/geometry/setYLength 1 cm
/gate/PETlayer/geometry/setZLength 1 cm
/gate/PETlayer/vis/forceWireframe 0
/gate/PETlayer/vis/forceSolid 1
/gate/PETlayer/vis/setColor yellow
/gate/PETlayer/vis/setVisible 1

# Repeaters crystal
/gate/PETcrystal/repeaters/insert cubicArray
/gate/PETcrystal/cubicArray/setRepeatNumberX 1
/gate/PETcrystal/cubicArray/setRepeatNumberY 2
/gate/PETcrystal/cubicArray/setRepeatNumberZ 4
/gate/PETcrystal/cubicArray/setRepeatVector 0 1 1 cm

# Repeaters smod
/gate/PETsmod/repeaters/insert cubicArray
/gate/PETsmod/cubicArray/setRepeatNumberX 1
/gate/PETsmod/cubicArray/setRepeatNumberY 3
/gate/PETsmod/cubicArray/setRepeatNumberZ 5
/gate/PETsmod/cubicArray/setRepeatVector 0 2 4 cm

# Repeaters mod
/gate/PETmodule/repeaters/insert cubicArray
/gate/PETmodule/cubicArray/setRepeatNumberX 1
/gate/PETmodule/cubicArray/setRepeatNumberY 1
/gate/PETmodule/cubicArray/setRepeatNumberZ 1
/gate/PETmodule/cubicArray/setRepeatVector 0 0 0 cm

# Repeaters module
/gate/PETrsector/repeaters/insert ring
/gate/PETrsector/ring/setRepeatNumber 32
/gate/PETrsector/ring/setFirstAngle 0 deg

# Attach system
/gate/systems/cylindricalPET/rsector/attach PETrsector
/gate/systems/cylindricalPET/module/attach PETmodule
/gate/systems/cylindricalPET/submodule/attach PETsmod
/gate/systems/cylindricalPET/crystal/attach PETcrystal
/gate/systems/cylindricalPET/layer0/attach PETlayer

/gate/PETlayer/attachCrystalSD
