# Available physics lists:
# https://geant4.web.cern.ch/documentation/dev/plg_html/PhysicsListGuide/physicslistguide.html

/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/addProcess RadioactiveDecay

/gate/physics/processList Enabled
/gate/physics/processList Initialized

# Cuts
/gate/physics/Gamma/SetCutInRegion PETcrystals 5 mm
/gate/physics/Electron/SetCutInRegion PETcrystals 5 mm
/gate/physics/Positron/SetCutInRegion PETcrystals 5 mm
